backend:
  name: github
  repo: wolfrobert35/jnj

media_folder: static/img
public_folder: /img

collections:
  - name: "mirror"
    label: "Zrcadlo"
    folder: "src/pages/products/mirror"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "single"}
      - {label: "Category", name: "category", widget: "hidden", default: "mirror"}
      - {label: "Název", name: "nazev", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Cena v CZK", name: "cena", widget: "number"}
      - {label: "Price in EUR", name: "price", widget: "number"}
      - {label: "Obrázek", name: "thumbnail", widget: "image"}

  - name: "photography"
    label: "Fotka"
    folder: "src/pages/products/photography"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "single"}
      - {label: "Category", name: "category", widget: "hidden", default: "photography"}
      - {label: "Název", name: "nazev", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Cena v CZK", name: "cena", widget: "number"}
      - {label: "Price in EUR", name: "price", widget: "number"}
      - {label: "Obrázek", name: "thumbnail", widget: "image"}

  - name: "jewellery"
    label: "Šprek"
    folder: "src/pages/products/jewellery"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "single"}
      - {label: "Category", name: "category", widget: "hidden", default: "jewellery"}
      - {label: "Název", name: "nazev", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Cena v CZK", name: "cena", widget: "number"}
      - {label: "Price in EUR", name: "price", widget: "number"}
      - {label: "Obrázek", name: "thumbnail", widget: "image"}

  - name: "glass"
    label: "Sklo"
    folder: "src/pages/products/glass"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "single"}
      - {label: "Category", name: "category", widget: "hidden", default: "mirror"}
      - {label: "Název", name: "nazev", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Cena v CZK", name: "cena", widget: "number"}
      - {label: "Price in EUR", name: "price", widget: "number"}
      - {label: "Obrázek", name: "thumbnail", widget: "image"}

  - name: "general"
    label: "Obecně"
    files:
      - file: "src/categories/general.md"
        label: "Hlavní stránka"
        name: "frontpage"
        fields:
          - label: "O nás"
            name: "about"
            widget: "object"
            fields:
              - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
              - {label: "Popis", name: "popis", widget: "text"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Úvodní fotka", name: "thumbnail", widget: "image"}
          - label: "Kontakt"
            name: "contact"
            widget: "object"
            fields:
              - {label: "Facebook", name: "facebook", widget: "string"}
              - {label: "Instagram", name: "instagram", widget: "string"}
              - {label: "Email", name: "email", widget: "string"}
              - {label: "Telefon", name: "phone", widget: "string"}
          - label: "Objednávka"
            name: "order"
            widget: "object"
            fields:
              - {label: "Objednávka", name: "objednavka", widget: "text"}
              - {label: "Order", name: "order", widget: "text"}
      - file: "src/categories/mirror.md"
        label: "Zrcadlo"
        name: "mirror-page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "page"}
          - {label: "Category", name: "category", widget: "hidden", default: "mirror"}
          - {label: "Popis", name: "popis", widget: "text"}
          - {label: "Description", name: "description", widget: "number"}
      - file: "src/categories/photography.md"
        label: "Zrcadlo"
        name: "photography-page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "page"}
          - {label: "Category", name: "category", widget: "hidden", default: "photography"}
          - {label: "Popis", name: "popis", widget: "text"}
          - {label: "Description", name: "description", widget: "number"}
      - file: "src/categories/jewellery.md"
        label: "Zrcadlo"
        name: "jewellery-page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "page"}
          - {label: "Category", name: "category", widget: "hidden", default: "jewellery"}
          - {label: "Popis", name: "popis", widget: "text"}
          - {label: "Description", name: "description", widget: "number"}
      - file: "src/categories/glass.md"
        label: "Zrcadlo"
        name: "glass-page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "page"}
          - {label: "Category", name: "category", widget: "hidden", default: "glass"}
          - {label: "Popis", name: "popis", widget: "text"}
          - {label: "Description", name: "description", widget: "number"}
